apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cjbh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cjbh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cjbh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cjbh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cjbh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nsaq-tenant/rhtap-demo-app/hacbs-test-project-cjbh@sha256:4f2e79831e527f96b163453357167fdd7cd7e86a502e4b18261c6285c25ae160
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
