apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cjbh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nsaq-tenant/rhtap-demo-app/hacbs-test-project-cjbh@sha256:2167aa98e9304022ed1ebb01267ee90fa4781329b370d8d16c6882815bec379f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
