apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cjbh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nsaq-tenant/rhtap-demo-app/hacbs-test-project-cjbh@sha256:4f2e79831e527f96b163453357167fdd7cd7e86a502e4b18261c6285c25ae160
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
